In [43]:
import pickle
import pandas as pd
from sklearn.metrics import classification_report
from sklearn import metrics

In [44]:
from sklearn.metrics import confusion_matrix

'a string'

In [45]:
model = pickle.load(open('data/classification.model', 'rb'))

In [46]:
y_test = pickle.load(open('data/y_test', 'rb'))

In [47]:
X_test = pickle.load(open('data/X_test', 'rb'))

In [20]:
#X_test_one = X_test.reshape(-1,1)

In [48]:
y_pred = model.predict(X_test)

34/34 [==============================] - 4s 87ms/step


In [49]:
def get_preds(y_pred):
    preds = []
    for i in range(0,len(y_pred)):
        max_p = -1
        max_i = -1
        for index, prob in enumerate(y_pred[i]):
            if prob > max_p:
                max_p = prob
                max_i = index
        preds.append(max_i)
    return preds


In [50]:
y_preds = get_preds(y_pred)


list

In [51]:
cr = classification_report(y_test, y_preds)

In [52]:
print(cr)

              precision    recall  f1-score   support

           0       0.94      0.95      0.94        95
           1       0.95      0.98      0.96       130
           2       0.95      0.97      0.96        59
           3       0.95      0.96      0.95        94
           4       0.98      0.97      0.97        95
           5       0.98      0.96      0.97       113
           6       0.97      0.95      0.96        75
           7       0.97      0.97      0.97       120
           8       0.94      0.88      0.91        52
           9       1.00      0.99      1.00       136
          10       0.97      0.98      0.97       116

    accuracy                           0.97      1085
   macro avg       0.96      0.96      0.96      1085
weighted avg       0.97      0.97      0.97      1085



In [53]:
print("Accuracy:", metrics.accuracy_score(y_test, y_preds))


Accuracy: 0.9658986175115207


In [54]:
print("Precision:", metrics.precision_score(y_test, y_preds,average='macro'))


Precision: 0.9632559041968315


In [55]:
print("Recall:", metrics.recall_score(y_test, y_preds,average='macro'))

Recall: 0.9602318686127199


In [56]:
cf = confusion_matrix(y_test, y_preds)
print(cf)

[[ 90   0   0   1   0   0   0   2   2   0   0]
 [  0 127   0   0   1   1   1   0   0   0   0]
 [  0   0  57   0   0   1   1   0   0   0   0]
 [  0   1   0  90   0   0   0   0   1   0   2]
 [  2   1   0   0  92   0   0   0   0   0   0]
 [  0   2   0   1   0 109   0   0   0   0   1]
 [  0   0   1   3   0   0  71   0   0   0   0]
 [  0   3   0   0   0   0   0 117   0   0   0]
 [  4   0   0   0   1   0   0   1  46   0   0]
 [  0   0   0   0   0   0   0   0   0 135   1]
 [  0   0   2   0   0   0   0   0   0   0 114]]


In [58]:
import json

In [61]:
json_file = "/home/bilbo/dev/python/audio_ml/audioml/data/speakers_11.json"

In [62]:
with open(json_file, 'r') as f:
    json_obj = json.load(f)

In [63]:
json_obj.keys()

dict_keys(['mapping', 'labels', 'mfcc'])

In [66]:
import pandas as pd

In [78]:
df = pd.read_json(json_file, orient="index")

In [80]:
df = df.T

In [81]:
df.columns

Index(['mapping', 'labels', 'mfcc'], dtype='object')

In [83]:
df['mapping']

0       m0005
1       m0003
2       f0002
3       f0004
4       m0002
        ...  
4333     None
4334     None
4335     None
4336     None
4337     None
Name: mapping, Length: 4338, dtype: object

In [96]:
df.groupby('labels').count()

mapping  mfcc
labels               
0            11   328
1             0   574
2             0   234
3             0   407
4             0   399
5             0   469
6             0   294
7             0   511
8             0   172
9             0   479
10            0   471

In [97]:
df.labels.value_counts()

1     574
7     511
9     479
10    471
5     469
3     407
4     399
0     328
6     294
2     234
8     172
Name: labels, dtype: int64